-- =========================================
-- Appliance Control MVP Schema (Simplified)
-- 4 tables: appliance_master, routine_master, routine_action, user_appliance_control
-- =========================================

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- =========================================
-- 1. appliance_master: 4종 가전 마스터 (읽기 전용)
-- =========================================
create table if not exists public.appliance_master (
  appliance_master_id bigint generated by default as identity primary key,
  appliance_code varchar(30) not null unique,
  appliance_name varchar(100) not null,
  appliance_description text,
  created_at timestamptz not null default now()
);

comment on table public.appliance_master is '지원 가전 타입 마스터. 세탁기, 건조기, 로봇청소기, 공기청정기 4종.';

-- =========================================
-- 2. routine_master: 3개 루틴 마스터 (읽기 전용)
-- =========================================
create table if not exists public.routine_master (
  routine_id bigint generated by default as identity primary key,
  routine_code varchar(30) not null unique,
  pregnancy_stage varchar(20) not null unique
    check (pregnancy_stage in ('EARLY', 'MIDDLE', 'LATE')),
  routine_name varchar(100) not null,
  routine_subtitle varchar(200),
  routine_description text,
  routine_detail_description text,
  created_at timestamptz not null default now()
);

comment on table public.routine_master is '임신 시기별 가전 루틴 마스터. 초기/중기/후기 3개.';

-- =========================================
-- 3. routine_action: 루틴별 가전 동작 정의 (읽기 전용)
-- =========================================
create table if not exists public.routine_action (
  routine_action_id bigint generated by default as identity primary key,
  routine_id bigint not null references public.routine_master(routine_id) on delete cascade on update cascade,
  appliance_master_id bigint not null references public.appliance_master(appliance_master_id) on delete restrict on update cascade,
  sequence_no integer not null check (sequence_no > 0),
  action_title varchar(100) not null,
  action_description text,
  target_power_state varchar(20),
  target_mode varchar(50),
  target_alert_sound varchar(20),
  created_at timestamptz not null default now(),
  unique (routine_id, sequence_no)
);

comment on table public.routine_action is '루틴별 각 가전의 동작 정의. 루틴 선택 시 가전이 어떻게 동작하는지 표시용.';

create index if not exists idx_routine_action_routine_sequence
  on public.routine_action(routine_id, sequence_no);

-- =========================================
-- 4. user_appliance_control: 사용자 가전 제어 상태
-- =========================================
create table if not exists public.user_appliance_control (
  user_appliance_control_id bigint generated by default as identity primary key,
  user_id integer not null references public.users(user_id) on delete cascade on update cascade,
  appliance_master_id bigint not null references public.appliance_master(appliance_master_id) on delete restrict on update cascade,
  routine_id bigint not null references public.routine_master(routine_id) on delete restrict on update cascade,
  routine_activated boolean not null default false,
  alert_sound_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, appliance_master_id)
);

comment on table public.user_appliance_control is '사용자별 가전 제어 상태. 루틴 선택 시 4개 가전에 대해 생성되며 알림음 개별 제어 가능.';

create index if not exists idx_user_appliance_control_user_id
  on public.user_appliance_control(user_id);

drop trigger if exists trg_user_appliance_control_updated_at on public.user_appliance_control;
create trigger trg_user_appliance_control_updated_at
before update on public.user_appliance_control
for each row
execute function public.set_updated_at();

-- =========================================
-- Seed: 가전 마스터 데이터 (4종)
-- =========================================
insert into public.appliance_master (appliance_code, appliance_name, appliance_description)
values
  ('WASHER', '세탁기', '세탁 및 알림음 제어가 가능한 세탁기'),
  ('DRYER', '건조기', '건조 모드 및 알림음 제어가 가능한 건조기'),
  ('ROBOT_VACUUM', '로봇청소기', '청소 모드 제어가 가능한 로봇청소기'),
  ('AIR_PURIFIER', '공기청정기', '공기 청정 모드 제어가 가능한 공기청정기')
on conflict (appliance_code) do update
set
  appliance_name = excluded.appliance_name,
  appliance_description = excluded.appliance_description;

-- =========================================
-- Seed: 루틴 마스터 데이터 (3개)
-- =========================================
insert into public.routine_master (routine_code, pregnancy_stage, routine_name, routine_subtitle, routine_description, routine_detail_description)
values
  ('PREG_EARLY_ROUTINE', 'EARLY', '임신 초기 루틴',
   '수면 방해 차단 ''올 무음'' 루틴',
   '입덧과 예민함이 큰 시기를 고려해 실내 공기와 소음을 부드럽게 관리하는 루틴입니다.',
   E'편안한 휴식이 더 중요한 시기입니다.\n공기청정기 소음·불빛을 끄고,\n로봇청소기와 세탁 종료 알림을 잠시 멈춥니다.'),
  ('PREG_MIDDLE_ROUTINE', 'MIDDLE', '임신 중기 루틴',
   '허리 굽힘 제로 ''노터치'' 세탁 루틴',
   '활동량이 늘어나는 시기에 맞춰 청소와 세탁 준비를 안정적으로 돕는 루틴입니다.',
   E'무거운 배로 오래 서 있기 힘든 시기입니다.\n세탁기에서 빨래를 꺼내 건조기로 옮기는 과정은\n임산부에게 큰 부담이 됩니다.\n세탁 후 건조가 자동으로 이어져,\n허리를 굽히고 오래 조작하는 부담을 덜어줍니다.'),
  ('PREG_LATE_ROUTINE', 'LATE', '임신 후기 루틴',
   '아기 옷 ''먼지 철벽 방어'' 루틴',
   '휴식과 출산 준비를 우선해 공기 관리와 저소음 환경 유지에 초점을 둔 루틴입니다.',
   E'태어날 아기를 위한 빨래가 부쩍 많아지는 시기입니다.\n아기 옷을 꺼내는 순간 공기청정기가 강하게 작동해,\n공기 중에 뜨는 먼지를 빠르게 줄여줍니다.')
on conflict (routine_code) do update
set
  pregnancy_stage = excluded.pregnancy_stage,
  routine_name = excluded.routine_name,
  routine_subtitle = excluded.routine_subtitle,
  routine_description = excluded.routine_description,
  routine_detail_description = excluded.routine_detail_description;

-- =========================================
-- Seed: 루틴 액션 데이터 (루틴당 4개, 총 12개)
-- =========================================
delete from public.routine_action
where routine_id in (
  select routine_id from public.routine_master
  where routine_code in ('PREG_EARLY_ROUTINE', 'PREG_MIDDLE_ROUTINE', 'PREG_LATE_ROUTINE')
);

insert into public.routine_action (
  routine_id, appliance_master_id, sequence_no,
  action_title, action_description,
  target_power_state, target_mode, target_alert_sound
)
select
  rm.routine_id, am.appliance_master_id, v.sequence_no,
  v.action_title, v.action_description,
  v.target_power_state, v.target_mode, v.target_alert_sound
from public.routine_master rm
join (
  values
    -- 초기 루틴
    ('PREG_EARLY_ROUTINE', 1, 'AIR_PURIFIER', '공기청정기 수면 모드',
     '실내 공기 질을 유지하면서 조용한 수면 모드로 전환합니다.', 'ON', 'SLEEP', 'OFF'),
    ('PREG_EARLY_ROUTINE', 2, 'ROBOT_VACUUM', '로봇청소기 저소음 청소',
     '생활 소음을 줄이기 위해 저소음 청소 모드로 설정합니다.', 'ON', 'QUIET_CLEAN', null),
    ('PREG_EARLY_ROUTINE', 3, 'WASHER', '세탁기 알림 끄기',
     '세탁 완료 알림음을 꺼서 자극을 줄입니다.', null, null, 'OFF'),
    ('PREG_EARLY_ROUTINE', 4, 'DRYER', '건조기 알림 끄기',
     '건조 완료 알림음을 꺼서 조용한 환경을 유지합니다.', null, null, 'OFF'),

    -- 중기 루틴
    ('PREG_MIDDLE_ROUTINE', 1, 'ROBOT_VACUUM', '로봇청소기 일반 청소',
     '활동이 많은 시간대에 맞춰 일반 청소 모드로 전환합니다.', 'ON', 'NORMAL_CLEAN', null),
    ('PREG_MIDDLE_ROUTINE', 2, 'WASHER', '세탁기 표준 코스 준비',
     '생활 빨래를 위한 표준 세탁 코스로 상태를 맞춥니다.', 'ON', 'STANDARD_WASH', null),
    ('PREG_MIDDLE_ROUTINE', 3, 'AIR_PURIFIER', '공기청정기 자동 모드 유지',
     '실내 활동이 많아지는 시기를 고려해 자동 운전 모드를 유지합니다.', 'ON', 'AUTO', null),
    ('PREG_MIDDLE_ROUTINE', 4, 'DRYER', '건조기 알림 끄기',
     '휴식 시간을 방해하지 않도록 알림음을 끕니다.', null, null, 'OFF'),

    -- 후기 루틴
    ('PREG_LATE_ROUTINE', 1, 'AIR_PURIFIER', '공기청정기 집중 케어 모드',
     '휴식 시간을 고려해 공기 질을 안정적으로 유지하는 집중 케어 모드를 적용합니다.', 'ON', 'AIR_CARE', 'OFF'),
    ('PREG_LATE_ROUTINE', 2, 'WASHER', '세탁기 알림 끄기',
     '수면과 휴식을 위해 세탁기 알림음을 비활성화합니다.', null, null, 'OFF'),
    ('PREG_LATE_ROUTINE', 3, 'DRYER', '건조기 저소음 건조 준비',
     '아기 옷감까지 고려한 저소음 건조 모드로 전환합니다.', 'ON', 'GENTLE_DRY', 'OFF'),
    ('PREG_LATE_ROUTINE', 4, 'ROBOT_VACUUM', '로봇청소기 충전 대기',
     '휴식 우선 상태를 위해 충전 도크 대기 모드로 전환합니다.', 'OFF', 'DOCKED', null)
) as v (
  routine_code, sequence_no, appliance_code,
  action_title, action_description,
  target_power_state, target_mode, target_alert_sound
) on rm.routine_code = v.routine_code
join public.appliance_master am
  on am.appliance_code = v.appliance_code;
