-- Supabase / PostgreSQL schema
-- Step 2 of migration: convert the current MySQL schema into PostgreSQL syntax.
-- Apply this in Supabase SQL Editor after the project is created.

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create table if not exists users (
  user_id integer generated by default as identity primary key,
  email varchar(100) not null unique,
  password varchar(255) not null,
  username varchar(50) not null,
  baby_nickname varchar(50),
  role varchar(20),
  created_at timestamptz default now(),
  due_date date
);

create table if not exists pregnancy_profiles (
  pregnancy_profile_id integer generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  due_date date not null,
  pregnancy_start_date date,
  last_menstrual_period date,
  conception_date date,
  status varchar(20) default 'ACTIVE',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

drop trigger if exists trg_pregnancy_profiles_updated_at on pregnancy_profiles;
create trigger trg_pregnancy_profiles_updated_at
before update on pregnancy_profiles
for each row
execute function set_updated_at();

create table if not exists family_groups (
  group_id integer generated by default as identity primary key,
  group_name varchar(100) not null,
  invite_code varchar(50) unique,
  created_at timestamptz default now(),
  user_id integer references users(user_id) on delete set null on update cascade
);

create table if not exists family_members (
  member_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  approval_status varchar(20),
  joined_at timestamptz default now()
);

create table if not exists pregnancy_diaries (
  diary_id integer generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  title varchar(200) not null,
  content text,
  image_url varchar(500),
  created_at timestamptz default now()
);

create table if not exists todos (
  todo_id integer generated by default as identity primary key,
  target_week integer not null,
  todo_name varchar(100) not null,
  description text,
  category varchar(50),
  is_active char(1) default 'Y',
  created_at timestamptz default now()
);

create table if not exists mom_bti_types (
  mbti_type_id integer generated by default as identity primary key,
  mbti_type varchar(4) not null unique,
  title varchar(100) not null,
  subtitle varchar(255),
  summary text not null,
  image varchar(255)
);

create table if not exists mom_bti (
  mbti_id integer generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  mbti_type_id integer references mom_bti_types(mbti_type_id) on delete set null on update cascade,
  mbti_result varchar(20),
  score_pr integer,
  score_tf integer,
  score_ic integer,
  score_em integer,
  tested_at date
);

create table if not exists community_posts (
  post_id integer generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  category varchar(30),
  title varchar(200) not null,
  content text,
  mbti_tag varchar(20),
  created_at timestamptz default now()
);

create table if not exists schedules (
  schedule_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  todo_id integer references todos(todo_id) on delete set null on update cascade,
  title varchar(200) not null,
  schedule_type varchar(30) default 'MANUAL',
  source_type varchar(20) default 'MANUAL',
  status varchar(20) default 'PENDING',
  memo text,
  start_date timestamptz,
  end_date timestamptz,
  created_at timestamptz default now()
);

create table if not exists cheer_messages (
  message_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  sender_id integer not null references users(user_id) on delete cascade on update cascade,
  content text not null,
  reaction_emoji varchar(50),
  created_at timestamptz default now()
);

create table if not exists home_appliances (
  appliance_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  appliance_name varchar(100) not null,
  appliance_type varchar(50),
  status varchar(20),
  setting_command_json text
);

create table if not exists appliance_routines (
  routine_id integer generated by default as identity primary key,
  appliance_id integer not null references home_appliances(appliance_id) on delete cascade on update cascade,
  routine_name varchar(100) not null,
  target_week integer,
  is_auto_yn char(1),
  execution_time time
);

create table if not exists ai_chat_logs (
  chat_id integer generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  question text,
  ai_answer text,
  created_at timestamptz default now()
);
