-- Supabase / PostgreSQL schema
-- users.group_id based family-group model

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create table if not exists users (
  user_id integer generated by default as identity primary key,
  email varchar(100) not null unique,
  password varchar(255) not null,
  username varchar(50) not null,
  baby_nickname varchar(50),
  role varchar(20),
  created_at timestamptz default now(),
  due_date date,
  current_week integer,
  group_id integer
);

create table if not exists family_groups (
  group_id integer generated by default as identity primary key,
  group_name varchar(100) not null,
  invite_code varchar(50) unique,
  created_at timestamptz default now(),
  user_id integer references users(user_id) on delete set null on update cascade
);

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'users'
      and constraint_name = 'users_group_id_fkey'
  ) then
    alter table users
      add constraint users_group_id_fkey
      foreign key (group_id) references family_groups(group_id)
      on delete set null
      on update cascade;
  end if;
end $$;

create table if not exists pregnancy_diaries (
  diary_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  author_user_id integer not null references users(user_id) on delete cascade on update cascade,
  title varchar(200) not null,
  content text not null,
  diary_date date not null,
  status text not null default 'published' check (status in ('published', 'hidden', 'deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create trigger trg_pregnancy_diaries_updated_at
before update on pregnancy_diaries
for each row
execute function set_updated_at();

create index if not exists idx_pregnancy_diaries_group_status_diary_date_created_at
  on pregnancy_diaries(group_id, status, diary_date desc, created_at desc);

create index if not exists idx_pregnancy_diaries_author_status_created_at
  on pregnancy_diaries(author_user_id, status, created_at desc);

create table if not exists pregnancy_diary_images (
  diary_image_id integer generated by default as identity primary key,
  diary_id integer not null references pregnancy_diaries(diary_id) on delete cascade on update cascade,
  bucket_name text not null,
  file_path text not null,
  original_file_name text,
  mime_type text,
  file_size bigint,
  is_thumbnail boolean not null default false,
  sort_order integer not null default 1,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_pregnancy_diary_images_file_path
  on pregnancy_diary_images(file_path);

create index if not exists idx_pregnancy_diary_images_diary_thumbnail_sort
  on pregnancy_diary_images(diary_id, is_thumbnail, sort_order);

create unique index if not exists uq_pregnancy_diary_images_thumbnail_per_diary
  on pregnancy_diary_images(diary_id)
  where is_thumbnail = true;

alter table pregnancy_diary_images
  alter column bucket_name set default 'pregnancy-diary-images';

create table if not exists todos (
  todo_id integer generated by default as identity primary key,
  target_week integer not null,
  todo_name varchar(100) not null,
  description text,
  created_at timestamptz default now()
);

create table if not exists my_list (
  my_list_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  title varchar(200) not null,
  my_list_date date not null,
  created_at timestamptz default now(),
  check_yn char(1) not null default 'N'
);

create table if not exists recommand_list (
  recommand_list_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  todo_id integer not null references todos(todo_id) on delete cascade on update cascade,
  current_week integer not null,
  check_yn char(1) not null default 'N',
  created_at timestamptz default now()
);

create unique index if not exists uq_recommand_list_group_user_todo_week
  on recommand_list(group_id, user_id, todo_id, current_week);

create table if not exists mom_bti_types (
  mbti_type_id integer generated by default as identity primary key,
  mbti_type varchar(4) not null unique,
  title varchar(100) not null,
  subtitle varchar(255),
  summary text not null,
  image varchar(255)
);

create table if not exists mom_bti (
  mbti_id integer generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  mbti_type_id integer references mom_bti_types(mbti_type_id) on delete set null on update cascade,
  mbti_result varchar(20),
  score_pr integer,
  score_tf integer,
  score_ic integer,
  score_em integer,
  tested_at date
);

create table if not exists mombti_question (
  question_id integer generated by default as identity primary key,
  question_text text not null,
  dimension varchar(2) not null,
  display_order integer not null,
  is_active char(1) not null default 'Y',
  created_at timestamptz default now()
);

create table if not exists mombti_choice (
  choice_id integer generated by default as identity primary key,
  question_id integer not null references mombti_question(question_id) on delete cascade on update cascade,
  choice_text varchar(100) not null,
  target_trait varchar(2) not null,
  score_value integer not null,
  display_order integer not null,
  created_at timestamptz default now()
);

create table if not exists mombti_result_profile (
  result_type varchar(10) primary key,
  title varchar(100) not null,
  subtitle varchar(255),
  summary text not null,
  strengths text,
  weaknesses text,
  recommended_tip text,
  image_url varchar(500),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

drop trigger if exists trg_mombti_result_profile_updated_at on mombti_result_profile;
create trigger trg_mombti_result_profile_updated_at
before update on mombti_result_profile
for each row
execute function set_updated_at();

create table if not exists mombti_test_attempt (
  attempt_id integer generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  result_type varchar(10) references mombti_result_profile(result_type) on delete set null on update cascade,
  score_p integer default 0,
  score_r integer default 0,
  score_t integer default 0,
  score_f integer default 0,
  score_i integer default 0,
  score_c integer default 0,
  score_e integer default 0,
  score_m integer default 0,
  status varchar(20) not null default 'IN_PROGRESS',
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists mombti_answer (
  answer_id integer generated by default as identity primary key,
  attempt_id integer not null references mombti_test_attempt(attempt_id) on delete cascade on update cascade,
  question_id integer not null references mombti_question(question_id) on delete cascade on update cascade,
  choice_id integer not null references mombti_choice(choice_id) on delete cascade on update cascade,
  target_trait varchar(2) not null,
  score_value integer not null,
  answered_at timestamptz default now()
);

create index if not exists idx_mombti_question_display_order
  on mombti_question(display_order);

create index if not exists idx_mombti_choice_question_order
  on mombti_choice(question_id, display_order);

create index if not exists idx_mombti_attempt_user_created_at
  on mombti_test_attempt(user_id, created_at desc);

create index if not exists idx_mombti_answer_attempt
  on mombti_answer(attempt_id);

create table if not exists boards (
  board_id integer generated by default as identity primary key,
  board_code varchar(30) not null unique,
  board_name varchar(100) not null,
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_boards_updated_at
before update on boards
for each row
execute function set_updated_at();

create table if not exists community_keywords (
  keyword_id integer generated by default as identity primary key,
  keyword_code varchar(30) not null unique,
  keyword_name varchar(100) not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_community_keywords_updated_at
before update on community_keywords
for each row
execute function set_updated_at();

create table if not exists community_posts (
  post_id integer generated by default as identity primary key,
  board_id integer not null references boards(board_id) on delete restrict on update cascade,
  keyword_id integer not null references community_keywords(keyword_id) on delete restrict on update cascade,
  author_user_id integer not null references users(user_id) on delete cascade on update cascade,
  author_mombti_result_type varchar(10) references mombti_result_profile(result_type) on delete set null on update cascade,
  title varchar(200) not null,
  content text not null,
  like_count integer not null default 0 check (like_count >= 0),
  comment_count integer not null default 0 check (comment_count >= 0),
  view_count integer not null default 0 check (view_count >= 0),
  is_anonymous boolean not null default false,
  status text not null default 'published' check (status in ('published', 'hidden', 'deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create trigger trg_community_posts_updated_at
before update on community_posts
for each row
execute function set_updated_at();

create table if not exists community_comments (
  comment_id integer generated by default as identity primary key,
  post_id integer not null references community_posts(post_id) on delete cascade on update cascade,
  author_user_id integer not null references users(user_id) on delete cascade on update cascade,
  content text not null,
  status text not null default 'published' check (status in ('published', 'hidden', 'deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create trigger trg_community_comments_updated_at
before update on community_comments
for each row
execute function set_updated_at();

create table if not exists community_post_likes (
  post_like_id integer generated by default as identity primary key,
  post_id integer not null references community_posts(post_id) on delete cascade on update cascade,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create index if not exists idx_community_posts_board_status_created_at
  on community_posts(board_id, status, created_at desc);

create index if not exists idx_community_posts_keyword_status_created_at
  on community_posts(keyword_id, status, created_at desc);

create index if not exists idx_community_posts_mombti_status_created_at
  on community_posts(author_mombti_result_type, status, created_at desc);

create index if not exists idx_community_comments_post_status_created_at
  on community_comments(post_id, status, created_at);

create index if not exists idx_community_post_likes_post_id
  on community_post_likes(post_id);

create index if not exists idx_community_post_likes_user_id
  on community_post_likes(user_id);

create table if not exists schedules (
  schedule_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  title varchar(200) not null,
  memo text,
  schedule_type varchar(20) not null,
  schedule_date date not null,
  "time" time not null,
  created_at timestamptz default now()
);

create unique index if not exists uq_schedules_due_date_per_group
  on schedules(group_id)
  where title = '출산 예정일' and schedule_type = '중요';

create table if not exists cheer_messages (
  message_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  sender_id integer not null references users(user_id) on delete cascade on update cascade,
  content text,
  reaction_emoji varchar(50),
  created_at timestamptz default now()
);

create table if not exists home_appliances (
  appliance_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  appliance_name varchar(100) not null,
  appliance_type varchar(50),
  status varchar(20),
  setting_command_json text
);

create table if not exists appliance_routines (
  routine_id integer generated by default as identity primary key,
  appliance_id integer not null references home_appliances(appliance_id) on delete cascade on update cascade,
  routine_name varchar(100) not null,
  target_week integer,
  is_auto_yn char(1),
  execution_time time
);

create table if not exists ai_chat_logs (
  chat_id integer generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  question text,
  ai_answer text,
  created_at timestamptz default now()
);
