-- Supabase / PostgreSQL schema
-- users.group_id based family-group model

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create table if not exists users (
  user_id integer generated by default as identity primary key,
  email varchar(100) not null unique,
  password varchar(255) not null,
  username varchar(50) not null,
  baby_nickname varchar(50),
  role varchar(20),
  created_at timestamptz default now(),
  due_date date,
  current_week integer,
  group_id integer
);

create table if not exists family_groups (
  group_id integer generated by default as identity primary key,
  group_name varchar(100) not null,
  invite_code varchar(50) unique,
  created_at timestamptz default now(),
  user_id integer references users(user_id) on delete set null on update cascade
);

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'users'
      and constraint_name = 'users_group_id_fkey'
  ) then
    alter table users
      add constraint users_group_id_fkey
      foreign key (group_id) references family_groups(group_id)
      on delete set null
      on update cascade;
  end if;
end $$;

create table if not exists pregnancy_diaries (
  diary_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  author_user_id integer not null references users(user_id) on delete cascade on update cascade,
  title varchar(200) not null,
  content text not null,
  diary_date date not null,
  status text not null default 'published' check (status in ('published', 'hidden', 'deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

drop trigger if exists trg_pregnancy_diaries_updated_at on pregnancy_diaries;
create trigger trg_pregnancy_diaries_updated_at
before update on pregnancy_diaries
for each row
execute function set_updated_at();

create index if not exists idx_pregnancy_diaries_group_status_diary_date_created_at
  on pregnancy_diaries(group_id, status, diary_date desc, created_at desc);

create index if not exists idx_pregnancy_diaries_author_status_created_at
  on pregnancy_diaries(author_user_id, status, created_at desc);

create table if not exists pregnancy_diary_images (
  diary_image_id integer generated by default as identity primary key,
  diary_id integer not null references pregnancy_diaries(diary_id) on delete cascade on update cascade,
  bucket_name text not null,
  file_path text not null,
  original_file_name text,
  mime_type text,
  file_size bigint,
  is_thumbnail boolean not null default false,
  sort_order integer not null default 1,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_pregnancy_diary_images_file_path
  on pregnancy_diary_images(file_path);

create index if not exists idx_pregnancy_diary_images_diary_thumbnail_sort
  on pregnancy_diary_images(diary_id, is_thumbnail, sort_order);

create unique index if not exists uq_pregnancy_diary_images_thumbnail_per_diary
  on pregnancy_diary_images(diary_id)
  where is_thumbnail = true;

alter table pregnancy_diary_images
  alter column bucket_name set default 'pregnancy-diary-images';

create table if not exists todos (
  todo_id integer generated by default as identity primary key,
  target_week integer not null,
  todo_name varchar(100) not null,
  description text,
  created_at timestamptz default now()
);

create table if not exists my_list (
  my_list_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  title varchar(200) not null,
  my_list_date date not null,
  created_at timestamptz default now(),
  check_yn char(1) not null default 'N'
);

create table if not exists recommand_list (
  recommand_list_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  todo_id integer not null references todos(todo_id) on delete cascade on update cascade,
  current_week integer not null,
  check_yn char(1) not null default 'N',
  created_at timestamptz default now()
);

create unique index if not exists uq_recommand_list_group_user_todo_week
  on recommand_list(group_id, user_id, todo_id, current_week);

create table if not exists mom_bti_types (
  mbti_type_id integer generated by default as identity primary key,
  mbti_type varchar(4) not null unique,
  title varchar(100) not null,
  subtitle varchar(255),
  summary text not null,
  image varchar(255)
);

create table if not exists mom_bti (
  mbti_id integer generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  mbti_type_id integer references mom_bti_types(mbti_type_id) on delete set null on update cascade,
  mbti_result varchar(20),
  score_pr integer,
  score_tf integer,
  score_ic integer,
  score_em integer,
  tested_at date
);

create table if not exists mombti_question (
  question_id integer generated by default as identity primary key,
  question_text text not null,
  dimension varchar(2) not null,
  display_order integer not null,
  is_active char(1) not null default 'Y',
  created_at timestamptz default now()
);

create table if not exists mombti_choice (
  choice_id integer generated by default as identity primary key,
  question_id integer not null references mombti_question(question_id) on delete cascade on update cascade,
  choice_text varchar(100) not null,
  target_trait varchar(2) not null,
  score_value integer not null,
  display_order integer not null,
  created_at timestamptz default now()
);

create table if not exists mombti_result_profile (
  result_type varchar(10) primary key,
  title varchar(100) not null,
  subtitle varchar(255),
  summary text not null,
  strengths text,
  weaknesses text,
  recommended_tip text,
  image_url varchar(500),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

drop trigger if exists trg_mombti_result_profile_updated_at on mombti_result_profile;
create trigger trg_mombti_result_profile_updated_at
before update on mombti_result_profile
for each row
execute function set_updated_at();

create table if not exists mombti_test_attempt (
  attempt_id integer generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  result_type varchar(10) references mombti_result_profile(result_type) on delete set null on update cascade,
  score_p integer default 0,
  score_r integer default 0,
  score_t integer default 0,
  score_f integer default 0,
  score_i integer default 0,
  score_c integer default 0,
  score_e integer default 0,
  score_m integer default 0,
  status varchar(20) not null default 'IN_PROGRESS',
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists mombti_answer (
  answer_id integer generated by default as identity primary key,
  attempt_id integer not null references mombti_test_attempt(attempt_id) on delete cascade on update cascade,
  question_id integer not null references mombti_question(question_id) on delete cascade on update cascade,
  choice_id integer not null references mombti_choice(choice_id) on delete cascade on update cascade,
  target_trait varchar(2) not null,
  score_value integer not null,
  answered_at timestamptz default now()
);

create index if not exists idx_mombti_question_display_order
  on mombti_question(display_order);

create index if not exists idx_mombti_choice_question_order
  on mombti_choice(question_id, display_order);

create index if not exists idx_mombti_attempt_user_created_at
  on mombti_test_attempt(user_id, created_at desc);

create index if not exists idx_mombti_answer_attempt
  on mombti_answer(attempt_id);

create table if not exists boards (
  board_id integer generated by default as identity primary key,
  board_code varchar(30) not null unique,
  board_name varchar(100) not null,
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_boards_updated_at on boards;
create trigger trg_boards_updated_at
before update on boards
for each row
execute function set_updated_at();

create table if not exists community_keywords (
  keyword_id integer generated by default as identity primary key,
  keyword_code varchar(30) not null unique,
  keyword_name varchar(100) not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_community_keywords_updated_at on community_keywords;
create trigger trg_community_keywords_updated_at
before update on community_keywords
for each row
execute function set_updated_at();

create table if not exists community_posts (
  post_id integer generated by default as identity primary key,
  board_id integer not null references boards(board_id) on delete restrict on update cascade,
  keyword_id integer not null references community_keywords(keyword_id) on delete restrict on update cascade,
  author_user_id integer not null references users(user_id) on delete cascade on update cascade,
  author_mombti_result_type varchar(10) references mombti_result_profile(result_type) on delete set null on update cascade,
  title varchar(200) not null,
  content text not null,
  like_count integer not null default 0 check (like_count >= 0),
  comment_count integer not null default 0 check (comment_count >= 0),
  view_count integer not null default 0 check (view_count >= 0),
  is_anonymous boolean not null default false,
  status text not null default 'published' check (status in ('published', 'hidden', 'deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

drop trigger if exists trg_community_posts_updated_at on community_posts;
create trigger trg_community_posts_updated_at
before update on community_posts
for each row
execute function set_updated_at();

create table if not exists community_comments (
  comment_id integer generated by default as identity primary key,
  post_id integer not null references community_posts(post_id) on delete cascade on update cascade,
  author_user_id integer not null references users(user_id) on delete cascade on update cascade,
  content text not null,
  status text not null default 'published' check (status in ('published', 'hidden', 'deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

drop trigger if exists trg_community_comments_updated_at on community_comments;
create trigger trg_community_comments_updated_at
before update on community_comments
for each row
execute function set_updated_at();

create table if not exists community_post_likes (
  post_like_id integer generated by default as identity primary key,
  post_id integer not null references community_posts(post_id) on delete cascade on update cascade,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create index if not exists idx_community_posts_board_status_created_at
  on community_posts(board_id, status, created_at desc);

create index if not exists idx_community_posts_keyword_status_created_at
  on community_posts(keyword_id, status, created_at desc);

create index if not exists idx_community_posts_mombti_status_created_at
  on community_posts(author_mombti_result_type, status, created_at desc);

create index if not exists idx_community_comments_post_status_created_at
  on community_comments(post_id, status, created_at);

create index if not exists idx_community_post_likes_post_id
  on community_post_likes(post_id);

create index if not exists idx_community_post_likes_user_id
  on community_post_likes(user_id);

create table if not exists schedules (
  schedule_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  title varchar(200) not null,
  memo text,
  schedule_type varchar(20) not null,
  schedule_date date not null,
  "time" time not null,
  created_at timestamptz default now()
);

create unique index if not exists uq_schedules_due_date_per_group
  on schedules(group_id)
  where title = '출산 예정일' and schedule_type = '중요';

create table if not exists cheer_messages (
  message_id integer generated by default as identity primary key,
  group_id integer not null references family_groups(group_id) on delete cascade on update cascade,
  sender_id integer not null references users(user_id) on delete cascade on update cascade,
  content text,
  reaction_emoji varchar(50),
  created_at timestamptz default now()
);

drop table if exists appliance_routines cascade;
drop table if exists home_appliances cascade;

-- =========================================
-- 가전 제어 테이블 (간소화 버전: 4개 테이블)
-- =========================================

create table if not exists appliance_master (
  appliance_master_id bigint generated by default as identity primary key,
  appliance_code varchar(30) not null unique,
  appliance_name varchar(100) not null,
  appliance_description text,
  created_at timestamptz not null default now()
);

comment on table appliance_master is '지원 가전 타입 마스터. 세탁기, 건조기, 로봇청소기, 공기청정기 4종.';

create table if not exists routine_master (
  routine_id bigint generated by default as identity primary key,
  routine_code varchar(30) not null unique,
  pregnancy_stage varchar(20) not null unique
    check (pregnancy_stage in ('EARLY', 'MIDDLE', 'LATE')),
  routine_name varchar(100) not null,
  routine_description text,
  created_at timestamptz not null default now()
);

comment on table routine_master is '임신 시기별 가전 루틴 마스터. 초기/중기/후기 3개.';

create table if not exists routine_action (
  routine_action_id bigint generated by default as identity primary key,
  routine_id bigint not null references routine_master(routine_id) on delete cascade on update cascade,
  appliance_master_id bigint not null references appliance_master(appliance_master_id) on delete restrict on update cascade,
  sequence_no integer not null check (sequence_no > 0),
  action_title varchar(100) not null,
  action_description text,
  target_power_state varchar(20),
  target_mode varchar(50),
  target_alert_sound varchar(20),
  created_at timestamptz not null default now(),
  unique (routine_id, sequence_no)
);

comment on table routine_action is '루틴별 각 가전의 동작 정의. 루틴 선택 시 가전이 어떻게 동작하는지 표시용.';

create table if not exists user_appliance_control (
  user_appliance_control_id bigint generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  appliance_master_id bigint not null references appliance_master(appliance_master_id) on delete restrict on update cascade,
  routine_id bigint not null references routine_master(routine_id) on delete restrict on update cascade,
  alert_sound_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, appliance_master_id)
);

comment on table user_appliance_control is '사용자별 가전 제어 상태. 루틴 선택 시 4개 가전에 대해 생성되며 알림음 개별 제어 가능.';

create index if not exists idx_user_appliance_control_user_id
  on user_appliance_control(user_id);

drop trigger if exists trg_user_appliance_control_updated_at on user_appliance_control;
create trigger trg_user_appliance_control_updated_at
before update on user_appliance_control
for each row execute function set_updated_at();

create index if not exists idx_routine_action_routine_sequence
  on routine_action(routine_id, sequence_no);

-- Seed: 가전 마스터 데이터
insert into appliance_master (appliance_code, appliance_name, appliance_description)
values
  ('WASHER', '세탁기', '세탁 및 알림음 제어가 가능한 세탁기'),
  ('DRYER', '건조기', '건조 모드 및 알림음 제어가 가능한 건조기'),
  ('ROBOT_VACUUM', '로봇청소기', '청소 모드 제어가 가능한 로봇청소기'),
  ('AIR_PURIFIER', '공기청정기', '공기 청정 모드 제어가 가능한 공기청정기')
on conflict (appliance_code) do update
set
  appliance_name = excluded.appliance_name,
  appliance_description = excluded.appliance_description;

-- Seed: 루틴 마스터 데이터
insert into routine_master (routine_code, pregnancy_stage, routine_name, routine_description)
values
  ('PREG_EARLY_ROUTINE', 'EARLY', '임신 초기 루틴',
   '입덧과 예민함이 큰 시기를 고려해 실내 공기와 소음을 부드럽게 관리하는 루틴입니다.'),
  ('PREG_MIDDLE_ROUTINE', 'MIDDLE', '임신 중기 루틴',
   '활동량이 늘어나는 시기에 맞춰 청소와 세탁 준비를 안정적으로 돕는 루틴입니다.'),
  ('PREG_LATE_ROUTINE', 'LATE', '임신 후기 루틴',
   '휴식과 출산 준비를 우선해 공기 관리와 저소음 환경 유지에 초점을 둔 루틴입니다.')
on conflict (routine_code) do update
set
  pregnancy_stage = excluded.pregnancy_stage,
  routine_name = excluded.routine_name,
  routine_description = excluded.routine_description;

-- Seed: 루틴 액션 데이터
delete from routine_action
where routine_id in (
  select routine_id from routine_master
  where routine_code in ('PREG_EARLY_ROUTINE', 'PREG_MIDDLE_ROUTINE', 'PREG_LATE_ROUTINE')
);

insert into routine_action (
  routine_id, appliance_master_id, sequence_no,
  action_title, action_description,
  target_power_state, target_mode, target_alert_sound
)
select
  rm.routine_id, am.appliance_master_id, v.sequence_no,
  v.action_title, v.action_description,
  v.target_power_state, v.target_mode, v.target_alert_sound
from routine_master rm
join (
  values
    ('PREG_EARLY_ROUTINE', 1, 'AIR_PURIFIER', '공기청정기 수면 모드',
     '실내 공기 질을 유지하면서 조용한 수면 모드로 전환합니다.', 'ON', 'SLEEP', 'OFF'),
    ('PREG_EARLY_ROUTINE', 2, 'ROBOT_VACUUM', '로봇청소기 저소음 청소',
     '생활 소음을 줄이기 위해 저소음 청소 모드로 설정합니다.', 'ON', 'QUIET_CLEAN', null),
    ('PREG_EARLY_ROUTINE', 3, 'WASHER', '세탁기 알림 끄기',
     '세탁 완료 알림음을 꺼서 자극을 줄입니다.', null, null, 'OFF'),
    ('PREG_EARLY_ROUTINE', 4, 'DRYER', '건조기 알림 끄기',
     '건조 완료 알림음을 꺼서 조용한 환경을 유지합니다.', null, null, 'OFF'),
    ('PREG_MIDDLE_ROUTINE', 1, 'ROBOT_VACUUM', '로봇청소기 일반 청소',
     '활동이 많은 시간대에 맞춰 일반 청소 모드로 전환합니다.', 'ON', 'NORMAL_CLEAN', null),
    ('PREG_MIDDLE_ROUTINE', 2, 'WASHER', '세탁기 표준 코스 준비',
     '생활 빨래를 위한 표준 세탁 코스로 상태를 맞춥니다.', 'ON', 'STANDARD_WASH', null),
    ('PREG_MIDDLE_ROUTINE', 3, 'AIR_PURIFIER', '공기청정기 자동 모드 유지',
     '실내 활동이 많아지는 시기를 고려해 자동 운전 모드를 유지합니다.', 'ON', 'AUTO', null),
    ('PREG_MIDDLE_ROUTINE', 4, 'DRYER', '건조기 알림 끄기',
     '휴식 시간을 방해하지 않도록 알림음을 끕니다.', null, null, 'OFF'),
    ('PREG_LATE_ROUTINE', 1, 'AIR_PURIFIER', '공기청정기 집중 케어 모드',
     '휴식 시간을 고려해 공기 질을 안정적으로 유지하는 집중 케어 모드를 적용합니다.', 'ON', 'AIR_CARE', 'OFF'),
    ('PREG_LATE_ROUTINE', 2, 'WASHER', '세탁기 알림 끄기',
     '수면과 휴식을 위해 세탁기 알림음을 비활성화합니다.', null, null, 'OFF'),
    ('PREG_LATE_ROUTINE', 3, 'DRYER', '건조기 저소음 건조 준비',
     '아기 옷감까지 고려한 저소음 건조 모드로 전환합니다.', 'ON', 'GENTLE_DRY', 'OFF'),
    ('PREG_LATE_ROUTINE', 4, 'ROBOT_VACUUM', '로봇청소기 충전 대기',
     '휴식 우선 상태를 위해 충전 도크 대기 모드로 전환합니다.', 'OFF', 'DOCKED', null)
) as v (
  routine_code, sequence_no, appliance_code,
  action_title, action_description,
  target_power_state, target_mode, target_alert_sound
) on rm.routine_code = v.routine_code
join appliance_master am
  on am.appliance_code = v.appliance_code;

create table if not exists ai_chat_logs (
  chat_id integer generated by default as identity primary key,
  user_id integer not null references users(user_id) on delete cascade on update cascade,
  question text,
  ai_answer text,
  created_at timestamptz default now()
);
