CREATE SEQUENCE THP_USER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE THP_USER (
    ID NUMBER(19, 0) PRIMARY KEY,
    LOGIN_ID VARCHAR2(50 CHAR) NOT NULL,
    PASSWORD_HASH VARCHAR2(255 CHAR) NOT NULL,
    NAME VARCHAR2(100 CHAR) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE THP_USER
    ADD CONSTRAINT UK_THP_USER_LOGIN_ID UNIQUE (LOGIN_ID);

CREATE OR REPLACE TRIGGER THP_USER_BU_TRG
    BEFORE UPDATE ON THP_USER
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSDATE;
END;
/

CREATE SEQUENCE THP_USER_SESSION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE THP_USER_SESSION (
    ID NUMBER(19, 0) PRIMARY KEY,
    USER_ID NUMBER(19, 0) NOT NULL,
    SESSION_TOKEN VARCHAR2(255 CHAR) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    EXPIRES_AT DATE NOT NULL,
    LAST_ACCESSED_AT DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE THP_USER_SESSION
    ADD CONSTRAINT UK_THP_USER_SESSION_TOKEN UNIQUE (SESSION_TOKEN);

ALTER TABLE THP_USER_SESSION
    ADD CONSTRAINT FK_THP_USER_SESSION_USER
    FOREIGN KEY (USER_ID)
    REFERENCES THP_USER (ID);

CREATE INDEX IX_THP_USER_SESSION_USER_ID
    ON THP_USER_SESSION (USER_ID);

CREATE INDEX IX_THP_USER_SESSION_EXPIRES_AT
    ON THP_USER_SESSION (EXPIRES_AT);
